from graphshw import WeightedGraph, WeightedDigraph
import random
from timeit import timeit

# Student Name: Parth Patel
#
# Programming Assignment 3
#
# Do not remove this comment that contains the detailed assignment instructions.
#
# What to Submit: Submit the following files once you complete
# the assignment:
# (a) Your modified graphshw.py which has your implementation of Dijkstra's algorithm.
# (b) Your completed shortestpathscomparison.py (don't rename either of these files).
# (c) A text file containing the table of timing results generated by the function
#     you implemented in step 2 of the assignment (see below).
# (d) Your answers to the questions from step 5 should either be in comments in this
#     file or a separate text file.
# (e) If you do the extra credit part, then make sure you include the additional .py
#     file with your extra credit solution, as well as your parser from assignment 2
#     (so I don't have to track it down again--actually I won't track it down, if you don't
#     include it with your submission I simply won't look at your extra credit).
# (f) You do NOT need to submit the other .py files that graphshw.py imports.  I gave
#     them to you. You are not modifying them. So I already have them.
#
# Do the following:
# (1) Implement Dijkstra's algorithm inside the _dijkstra method within the WeightedGraph
#    class of graphshw.py. Do not change the method name, its parameters, etc. See
#    comments inside that method for details.
#
# (2) Implement the time_shortest_path_algs function later in this file to do the following:
#     -- Call random_weighted_graph that I provided below to generate a random 
#        weighted graph with 64 vertices and 2016 edges (i.e., completely connected--all
#        possible undirected edges, other than loops) and weights random in interval
#        1 to 100 inclusive.
#     -- Read documentation of timeit (https://docs.python.org/3/library/timeit.html)
#        And also watch the videos I posted explaining its usage.
#     -- Use timeit to time two versions of Dijkstra's algorithm, specifically
#        the method, _dijkstra, that you implemented is called by dijkstra_binheap and
#        dijkstra_array. The dijkstra_binheap method passes a binary heap implementation
#        of a priority queue to your _dijkstra method. And dijkstra_array passes a simple
#        array implementation of a priority queue. Time both of these on this random graph.
#        I already imported the graphshw module at the top.
#     -- The number parameter to timeit controls how many times the thing you're
#        timing is called. To get meaningful times, you will need to experiment with this
#        a bit. E.g., increase it if the times are too small.  Use the same
#        value of number for timing both versions of Dijkstra's Algorithm.
#        IMPORTANT: Definitely don't use the default value of number, which is
#        something like 1000000 (e.g., the sun might explode before your program
#        finishes on the larger graphs below if you leave it at 10000000).
#     -- Make sure you don't include the time to generate the weighted graph in your
#        times.
#     -- Now repeat this for a graph with 128 vertices and 8128 edges.
#     -- Now repeat this for a graph with 256 vertices and 32640 edges.
#     -- Now repeat this for a graph with 512 vertices and 130816 edges.
#     -- Now repeat this for a graph with 1024 vertices and 523776 edges.
#     -- Repeat this again for 64 vertices and 128 edges.
#     -- Repeat yet again with 128 vertices and 256 edges.
#     -- Repeat yet again with 256 vertices and 512 edges.
#     -- Repeat yet again with 512 vertices and 1024 edges.
#     -- Repeat yet again with 1024 vertices and 2048 edges.
#    
#     -- Have the time_shortest_path_algs function output the timing data in a
#        table, with columns for number of vertexes, number of edges, time for the
#        binary heap version of Dijkstra, and time for the array version of Dijkstra.
#     -- If you want, you can include larger graphs.
#        The pattern I used when indicating what size to use:
#        Dense graphs: v, e=v*(v-1)/2.
#        Sparse: v, e=2*v.
#        For example, if you want to continue the experimentation with
#        larger graphs, you might
#        try 2048 vertices with 2096128 edges (dense graph),
#        2048 vertices with 4096 edges (sparse).
#     -- When you are timing the algorithms you can pass whatever vertex id you
#        want as the source vertex.  It shouldn't affect the runtime by much,
#        if at all. The random weighted graphs are such that there exists paths
#        to any destination from any source, even the sparse graphs, so timing
#        data shouldn't be affected much by source vertex.
#
# (3) Write some code in the if main block at the bottom of this file
#     to test that your Dijkstra implementation works correctly. You will actually
#     need to call dijkstra_binheap and dijkstra_array, and not your _dijkstra directly.
#     I suggest constructing a WeightedGraph from one of the textbook examples since you
#     know the correct solution to those. If g is a WeightedGraph, you can call
#     dijkstra_binheap with a source vertex of 0, with something like:
#     result = g.dijkstra_binheap(0), and similarly for dijkstra_array.
#
# (4) After that code, but in your if main block, call your function that
#     generates the timing data. Make sure you save that output to a text file.
#     If you run in IDLE, then just copy and paste from the shell into a text file.
#     If you run from the command line, you can just redirect the output to a text file.
#
# (5) Once you have the timing data, answer these questions, either right here in comments
#     or as a separate text file:
#     (a) Given the asymptotic runtimes (i.e., the big-O analysis) for the two versions
#         of Dijkstra's Algorithm, when should you expect Dijkstra with a binary heap
#         to be faster (e.g., in terms of graph density)? When should Dijkstra with a simple
#         array to be faster (e.g., in terms of graph density)? This question concerns the
#         Big-O runtimes of the algorithms, and not your timing data.
#     (b) Does graph density affect performance? In other words, using your timing data,
#         was one algorithm faster for dense graphs, but the other for sparse graphs? Or
#         was the same algorithm faster in both cases?
#     (c) Does size, in number of vertexes of the graph, affect performance? In other words,
#         using your timing data, was one algorithm always faster than the other? Or was one
#         faster for a low number of vertexes and the other faster when the number of vertexes
#         was higher?
#     (d) Are your timing results consistent with your answer to question (a)?
#         If not, what do you think caused the discrepancy?
#
# (6) OPTIONAL STEP (up to 15 points extra credit): In programming assignment 2, you
#     implemented a parser for some highway graph data files. Implement another python
#     module (i.e., another .py file) with an if main block where you: (a) get a highway
#     graph filename from the command line, (b) use your parser from assignment 2 to get a
#     WeightedGraph (you'll need an import statement for your parser), and (c) use either
#     version of Dijkstra to compute the Single Source Shortest Paths for the source
#     vertex of your choice.

def random_weighted_graph(v,e,min_w,max_w) :
    """Generates and returns a random weighted
    graph with v vertices and e different edges.

    Keyword arguments:
    v - number of vertices
    e - number of edges
    min_w - minimum weight
    max_w - maximum weight
    """

    edges = [ (random.randrange(0,i),i) for i in range(1,v) ]

    # if desired number of edges greater than length of current edge list, then add more edges
    if e > len(edges) :
        edgeSet = { x for x in edges }
        notYetUsedEdges = [ (y,x) for x in range(1,v) for y in range(x) if (y,x) not in edgeSet ]
        random.shuffle(notYetUsedEdges)
        count = e - len(edges)
        count = min(count, len(notYetUsedEdges))
        for i in range(count) :
            edges.append(notYetUsedEdges.pop())

    # generate random edge weights
    weights = [ random.uniform(min_w, max_w) for x in range(len(edges)) ]

    # construct a Digraph with the lists of edges and weights generated
    G = WeightedGraph(v, edges, weights)
    return G


def time_shortest_path_algs() :
    """Generates a table of timing results comparing two versions of Dijkstra"""

    # I will not be instantiating any of the graphs just yet, so they are all equal to None
    # Note: g1, g7, g8, and g14 are my own graphs that I added
    g1 = g2 = g3 = g4 = g5 = g6 = g7 = g8 = g9 = g10 = g11 = g12 = g13 = g14 = None

    # This will store all the vertex-counts and edge-counts together,
    # so that way I can correctly randomly generate a graph in the with-block later on
    # Note: the final ordered pair of (2048, 2096128) is my own dense graph that I added
    vertex_and_edge_counts = [(32, 496),
                              (64, 2016),
                              (128, 8128),
                              (256, 32640),
                              (512, 130816),
                              (1024, 523776),
                              (2048, 2096128),
                              (32, 64),
                              (64, 128),
                              (128, 256),
                              (256, 512),
                              (512, 1024),
                              (1024, 2048),
                              (2048, 4096)]


    # I will be traversing each graph in the outer for-loop of the with-block
    graphs = [g1,g2,g3,g4,g5,g6,g7,g8,g9,g10,g11,g12,g13,g14]


    # These are the corresponding numbers of trials of randomly generated graphs
    # that I am creating for each type of graph
    # (I will run Dijkstra's only once on each generated graph)
    # So basically:
    #   g1 = 200 trials
    #   g2 = 200 trials
    #   g3 = 100 trials
    #   g4 = 100 trials
    #   g5 = 50 trials
    #   g6 = 50 trials
    #   g7 = 30 trials
    #   g8 = 1000 trials
    #   g9 = 900 trials
    #   g10 = 500 trials
    #   g11 = 250 trials
    #   g12 = 200 trials
    #   g13 = 200 trials
    #   g14 = 100 trials
    # I had to decrease the number of trials as the number of vertices and edges
    # increased, because it would take way too long for my computer to calculate
    # times otherwise
    number_of_trials = [200,200,100,100,50,50,30,1000,900,500,250,200,200,100]

    # This list is for testing purposes only:
    # number_of_trials = [1,1,1,1,1,1,1,1,1,1,1,1,1,1]


    # This margin will be used to format the file.write() statements in the with-block
    margin = 5

    # This will store the names of each header, so I can format them in the with-block
    headers = ["#_of_Vertices", "#_of_Edges", "Dijkstra's_(Array)_(in seconds)", "Dijkstra's_(BinHeap)_(in seconds)"]


    # We will write to the "table.txt" file in this with-block
    with open("table.txt", "w") as file:

        # These series of file.write() statements will create a header for the
        # table in the text file
        file.write(f"{headers[0]:<{margin * 4}}|"
                   f"{headers[1]:<{margin * 4}}|"
                   f"{headers[2]:<{margin * 7}}|"
                   f"{headers[3]:<{margin * 7}}")
        file.write("\n")

        # This for-loop will add a dividing line between the header and the
        # rest of the values of the table in the text file
        for i in range(120):
            if i == 20 or i == 41 or i == 77:
                file.write("|")
                continue
            file.write("-")
        file.write("\n")


        # We will traverse each version of the undirected graph with
        # this outer for-loop
        for i, graph in enumerate(graphs):


            # This will keep track of the total time it takes for
            # all trials for a particular graph when using the array
            # version of the priority queue
            array_dijkstra_time = 0

            # This will keep track of the total time it takes for
            # all trials for a particular graph when using the binary heap
            # version of the priority queue
            binheap_dijkstra_time = 0

            # This for loop will generate a certain number of random weighted
            # graphs based on whatever the number of vertices and edges are
            # on this current iteration. We will traverse each version of the
            # graph and sum up the total time it takes in seconds using timeit
            for j in range(number_of_trials[i]):
                vertices, edges = vertex_and_edge_counts[i]
                graph = random_weighted_graph(vertices, edges, 1, 100)
                array_dijkstra_time += timeit(lambda: graph.dijkstra_array(0), number=1)
                graph = random_weighted_graph(vertices, edges, 1, 100)
                binheap_dijkstra_time += timeit(lambda: graph.dijkstra_binheap(0), number=1)

            # This will print out each section of the table for each version of the graph
            # Note: I am dividing array_dijkstra_time and binheap_dijkstra_time by the
            # number_of_trials, since I need to find the average time
            file.write(
                f"{vertices :< {margin * 4}}|"
                f"{edges :< {margin * 4}}|"
                f"{array_dijkstra_time / number_of_trials[i] :< {margin * 7}.8f}|"
                f"{binheap_dijkstra_time / number_of_trials[i] :< {margin * 7}.8f}")
            file.write("\n")



if __name__ == "__main__" :
    # Here is where you write some code to test that your algorithms
    # are correct.
    #
    # It is also where you will call your time_shortest_path_algs function.
    # Don't forget to save output to a text file.


    # Here is my code for testing both the array version and binary min heap
    # version of Dijkstra's algorithm. I tested this on Question 10 from Exam 2.
    # Note: I changed that graph to a weighted undirected graph instead of keeping
    # it as a weighted directed graph since that is the type of graph that we will
    # be testing later on, based on the random_weighted_graph method. So, I just
    # ignored that the edges on this graph were directed, and decided to imagine
    # them as undirected.
    # Here is how I mapped each vertex of that graph to a numerical vertex ID:
    #   A = 0
    #   B = 1
    #   C = 2
    #   D = 3
    #   E = 4

    edges = [(0, 1),(0, 2),(1, 2),(1, 3),(2, 4),(4, 1),(4, 3)]
    weights = [1, 4, 2, 6, 1, 1, 2]

    weighted_graph = WeightedGraph(5, edges, weights)

    djikstra_results_binheap = weighted_graph.dijkstra_binheap(0)

    djikstra_results_array = weighted_graph.dijkstra_array(0)

    print("Dijkstra's Algorithm (Binary Min Heap Version)")
    print("Question 10 of Exam 2 (weighted undirected graph version) : ")
    print("Format:")
    print("ID, d, pi")
    for v in djikstra_results_binheap:
        print(v)

    print("\n\n")

    print("Dijkstra's Algorithm (Array Version)")
    print("Question 10 of Exam 2 (weighted undirected graph version) : ")
    print("Format:")
    print("ID, d, pi")
    for v in djikstra_results_array:
        print(v)

    print("\n\n")

    # Here is another part of my code for testing both the array version and binary min heap
    # version of Dijkstra's algorithm. Since you suggested in the comments above that we should
    # pick a problem from the textbook to try Dijkstra's algorithm, I chose Figure 22.6 from
    # page 621. Here is how I mapped each vertex of that graph to a numerical vertex ID:
    #   s = 0
    #   t = 1
    #   x = 2
    #   y = 3
    #   z = 4
    # This time, I will be used the WeightedDigraph object instead of a regular WeightedGraph,
    # since that is what the book uses for this example for Dijkstra's algorithm.

    edges = [(0,1),(0,3),(1,2),(1,3),(2,4),(3,1),(3,2),(3,4),(4,0),(4,2)]
    weights = [10,5,1,2,4,3,9,2,7,6]

    weighted_graph = WeightedDigraph(5, edges, weights)

    djikstra_results_binheap = weighted_graph.dijkstra_binheap(0)

    djikstra_results_array = weighted_graph.dijkstra_array(0)

    print("Dijkstra's Algorithm (Binary Min Heap Version)")
    print("Figure 22.6 from page 621 (weighted digraph version) : ")
    print("Format:")
    print("ID, d, pi")
    for v in djikstra_results_binheap:
        print(v)

    print("\n\n")

    print("Dijkstra's Algorithm (Array Version)")
    print("Figure 22.6 from page 621 (weighted digraph version) : ")
    print("Format:")
    print("ID, d, pi")
    for v in djikstra_results_array:
        print(v)


    # This method will run the time_shortest_path_algs()
    # method, which will print out a table of the data
    # to a text file called table.txt

    time_shortest_path_algs()

    pass
